# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "panomic"
BBFILE_PATTERN_panomic := "^${LAYERDIR}/"
BBFILE_PRIORITY_panomic = "11"

LAYERSERIES_COMPAT_panomic = " scarthgap"

