# configuration file for Weston

#[autolaunch]
#path=/usr/bin/your-application
#[core]
#backend=drm-backend.so          # Set the backend to drm-backend.so
#xwayland=true                   # Keep XWayland enabled (optional, based on your use case)
#require-input=false             # Set to true if you want to require input devices
[core]
xwayland=true
backend=drm-backend.so
shell=kiosk-shell.so
xwayland=true
idle-time=0
use-g2d=0

#[shell]
#panel-position=top

#[output]
#name=HDMI-A-1
#mode=1920x1080
[xwayland]
path=/usr/bin/Xwayland

# Remove the [output] section to allow automatic detection
# Weston will automatically detect the connected output devices
